### ISSUE TITLE
Add orionoid scraper 

### ISSUE THREAD

**Issue by Jackstuch1990** [Ferrite-iOS/Ferrite#10]
Would you be able to add the Orion scraper to the app it’s a premium scraper but you can get a free account that should be good enough for most people.

**Comment by kingbri1** [comment]
Hi there,
Ferrite does not host any sources by default. Please ask about sources to the appropriate source dev on the **source** repository or in the **Ferrite Discord**.

This issues section is only for issues and requests for the app.

Closing this issue.
