### ISSUE TITLE
Opening Magnet URLs with iTorrent

### ISSUE THREAD

**Issue by theMaddis** [Ferrite-iOS/Ferrite#16]
Please add ‘open with iTorrent’ under magnet options

**Comment by kingbri1** [comment]
@theMaddis please reference #17. You can create a deeplink action with the latest nightly of Ferrite. If you have any questions, please ask in Discord.

**Comment by theMaddis** [comment]
Awesome, thanks. Appreciate all your hard work. Will check it out now.
