### ISSUE TITLE
No love for Android?

### ISSUE THREAD

**Issue by onlytanmoy** [Ferrite-iOS/Ferrite#30]
Hi, I just checked this reddit post https://www.reddit.com/r/RealDebrid/comments/157y187/how_to_search_and_stream_torrents_on_ios_with/ 
The app looks impressive but I understand its only for iOS devices at the moment, any plans to make it available for android users like me? :)

**Comment by socksprox** [comment]
Android has so many options, on iOS we nearly have nothing. 

Just use stremio with torrentio and setup your real debrid key. You will have an experience a 10000 times better

for movies and series only

**Comment by kingbri1** [comment]
Ferrite is made to be a clean and native experience for iOS only. If you'd like something similar on android, I'd recommend [Unchained](https://github.com/LivingWithHippos/unchained-android) or Stremio like the person said above.
